'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductID As String
    Public Property Name As String
    Public Property ShortDescription As String
    Public Property LongDescription As String
    Public Property CategoryID As String
    Public Property ImageFile As String
    Public Property UnitPrice As Decimal
    Public Property OnHand As Integer

End Class
